# https://github.com/actions/javascript-action

name: 'Ensure SHA Pinned Actions'
description: 'Ensure that GitHub Actions are pinned to full length commit SHAs'
author: 'Zennon Gosalvez'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: shield
  color: gray-dark
inputs:
  white-listed-actions:
    description: 'List of repos and actions that WILL NOT trigger a commit SHA pin failure. Each entry must be on a newline.'
    required: false
