# https://github.com/actions/javascript-action

name: 'Ensure SHA Pinned Actions'
description: 'Ensure that GitHub Actions are pinned to full length commit SHAs'
author: 'Zennon Gosalvez'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: shield
  color: gray-dark
inputs:
  allowlist:
    description: 'The list of owners or repositories that will be ignored and will not throw an error. Each entry must be on a new line. Optional. Default: `` (deny all)'
  dry_run:
    description: 'Set to `true` to show warnings instead of failing. Optional. Default: `false` (fail on any error)'
    default: false
